config/routes.rb
Classified::Application.routes.draw do
  resources :users

  resources :averts

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/avert.rb
class Avert < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :email, :password_digest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/averts_controller.rb
class AvertsController < ApplicationController
  # GET /averts
  # GET /averts.json
  def index
    @averts = Avert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @averts }
    end
  end

  # GET /averts/1
  # GET /averts/1.json
  def show
    @avert = Avert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @avert }
    end
  end

  # GET /averts/new
  # GET /averts/new.json
  def new
    @avert = Avert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @avert }
    end
  end

  # GET /averts/1/edit
  def edit
    @avert = Avert.find(params[:id])
  end

  # POST /averts
  # POST /averts.json
  def create
    @avert = Avert.new(params[:avert])

    respond_to do |format|
      if @avert.save
        format.html { redirect_to @avert, notice: 'Avert was successfully created.' }
        format.json { render json: @avert, status: :created, location: @avert }
      else
        format.html { render action: "new" }
        format.json { render json: @avert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /averts/1
  # PUT /averts/1.json
  def update
    @avert = Avert.find(params[:id])

    respond_to do |format|
      if @avert.update_attributes(params[:avert])
        format.html { redirect_to @avert, notice: 'Avert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @avert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /averts/1
  # DELETE /averts/1.json
  def destroy
    @avert = Avert.find(params[:id])
    @avert.destroy

    respond_to do |format|
      format.html { redirect_to averts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/averts_helper.rb
module AvertsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/averts/_form.html.erb
<%= form_for(@avert) do |f| %>
  <% if @avert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avert.errors.count, "error") %> prohibited this avert from being saved:</h2>

      <ul>
      <% @avert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/averts/edit.html.erb
<h1>Editing avert</h1>

<%= render 'form' %>

<%= link_to 'Show', @avert %> |
<%= link_to 'Back', averts_path %>

app/views/averts/index.html.erb
<h1>Listing averts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @averts.each do |avert| %>
  <tr>
    <td><%= avert.name %></td>
    <td><%= avert.description %></td>
    <td><%= link_to 'Show', avert %></td>
    <td><%= link_to 'Edit', edit_avert_path(avert) %></td>
    <td><%= link_to 'Destroy', avert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Avert', new_avert_path %>

app/views/averts/new.html.erb
<h1>New avert</h1>

<%= render 'form' %>

<%= link_to 'Back', averts_path %>

app/views/averts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @avert.name %>
</p>

<p>
  <b>Description:</b>
  <%= @avert.description %>
</p>


<%= link_to 'Edit', edit_avert_path(@avert) %> |
<%= link_to 'Back', averts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classified</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password digest</th>
    <th>Admin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password_digest %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Admin:</b>
  <%= @user.admin %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>